# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(384, 481)
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonWindow1 = QtWidgets.QPushButton(self.centralwidget)
        self.buttonWindow1.setGeometry(QtCore.QRect(80, 130, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(16)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.buttonWindow1.setFont(font)
        self.buttonWindow1.setAutoFillBackground(False)
        self.buttonWindow1.setObjectName("buttonWindow1")
        self.buttonWindow2 = QtWidgets.QPushButton(self.centralwidget)
        self.buttonWindow2.setGeometry(QtCore.QRect(80, 230, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(16)
        self.buttonWindow2.setFont(font)
        self.buttonWindow2.setObjectName("buttonWindow2")
        self.buttonWindow3 = QtWidgets.QPushButton(self.centralwidget)
        self.buttonWindow3.setGeometry(QtCore.QRect(80, 330, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(16)
        self.buttonWindow3.setFont(font)
        self.buttonWindow3.setObjectName("buttonWindow3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 384, 21))
        self.menubar.setObjectName("menubar")
        Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "MainWindow"))
        self.buttonWindow1.setText(_translate("Menu", "Video Pleer"))
        self.buttonWindow2.setText(_translate("Menu", "Music Pleer"))
        self.buttonWindow3.setText(_translate("Menu", "Have Fun"))
        self.label.setText(_translate("Menu", "PyQT5 Project"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Ui_Menu()
    ex.show()
    sys.exit(app.exec_())
